### ISSUE TITLE
http triggers

### ISSUE THREAD

**Issue by shehabghazy** [automatisch/automatisch#1029]
Hi guys

Thanks for making such a great tool , I have question on about http triggers, is it in plan to create a trigger as http webhook to kick off a workflow

In some cases like database integration it will be heavy load to check it periodically on intervals

Best regards

**Comment by barinali** [comment]
Hey @shehabghazy, thanks for your kind words!

We already have webhook and HTTP request integrations available in v0.5.0. We have also improved them and will release a newer version with the improvements in the foreseeable future.

Is there anything, in particular, you seek on top of the existing functionalities?

**Comment by shehabghazy** [comment]
perfect thank you very much .. just if there is an example for it in the documentation kindly send it to me

**Comment by barinali** [comment]
@shehabghazy, here is [a documentation page](https://automatisch.io/docs/guide/create-flow) you can follow to understand how to arrange a flow (using typeform and slack) in Automatisch. If you need help with installation on your local computer, you can refer to [the installation page](https://automatisch.io/docs/guide/installation).

As there is no specific documentation page to describe how to use webhook and/or HTTP request steps, I could only share this information above so that you can follow the same/similar steps for the triggers/actions you'd like.

[Here](https://automatisch.io/docs/apps/deepl/actions) you can find the list of applications along with the supported triggers, actions and pages describing how to connect them.

**Comment by shehabghazy** [comment]
@barinali got it thanks a lot
