### ISSUE TITLE
HTTP request get method

### ISSUE THREAD

**Issue by shehabghazy** [automatisch/automatisch#1072]
Hey guys, Thanks for your continued cooperation

I tried to get data from this trial API but it retaurns 400 :
https://www.fanpagekarma.com/api/v1/facebook/6815841748/kpi?token=abcdefghijklmnopqrstuvwxyz
It works well with postman and also in the browser, but it looks like it doesn't see the query param `token`

Is there any suggesion about that ?

**Comment by barinali** [comment]
@shehabghazy I see that the HEAD request we make to that URL responds with HTTP 400; thus, you see HTTP 400 in the output. We utilize a HEAD request to make sure the response we're about to get isn't over 25 MB. It looks like we need to iterate this.

**Comment by barinali** [comment]
@shehabghazy I have merged some branches around this topic, and your use case should be covered as of those changes.

However, I played around with fanpagekarma.com's API and had interesting findings. Automatisch HTTP-request action relies on the given content type (via the user interface) or the one we get from the HEAD request we make to the given URL. In your case, we cannot make a HEAD request to the given URL because the API doesn't support it. However, we cannot also provide a `content-type: application/json` because it rejects it even though its response is `application/json`!? Since this looks like an edge case we don't have enough samples of, I suggest you use `content-type: text/plain`, which will provide you with the API response in JSON format.

Feel free to re-open this issue (as it's auto-closed upon merging the referring pull request's branch) if we have more to cover around this.

**Comment by shehabghazy** [comment]
perfect, thanks a lot @barinali, everything is going well now 

cheers
