### ISSUE TITLE
error when adding new user 

### ISSUE THREAD

**Issue by asccreative** [automatisch/automatisch#1414]
On prem self-hosted version, when we Create a second user, we receive error; "Cannot read properties of undefined (reading "id"). Any help is appreciated.

**Comment by barinali** [comment]
Throughout iterations, we introduced a bug with user creation in self-hosted OSS Automatisch, which is already fixed in the main branch. However, it has yet to be released under a new version.

While I suggest you wait until a new release, one may also create a user on the database level in case of urgent need.

**Comment by farukaydin** [comment]
@asccreative we just released the new version of Automatisch, so it should be solved.

I'm closing this for now, but feel free to reopen or create a new issue in case of a problem.

**Comment by asccreative** [comment]
Thank you for letting us know. 





----- Original Message -----
