### ISSUE TITLE
Please add Salesforce Integration - this has gotta to be the #1 in enterprise applications

### ISSUE THREAD

**Issue by webyahoo** [automatisch/automatisch#1424]
We can help/contribute to the integration too. As we are a Salesforce Consulting group. 

swu@iotent.com

**Comment by barinali** [comment]
An integration for Salesforce already exists with three actions and a trigger. You may find them on the following links;

- https://automatisch.io/docs/apps/salesforce/connection
- https://automatisch.io/docs/apps/salesforce/triggers
- https://automatisch.io/docs/apps/salesforce/actions (it doesn't show the missing third action yet, which is to execute queries on Salesforce)

However, please feel free to contribute more actions and/or triggers or just mention them here so that we know what you'd like to have.
