### ISSUE TITLE
Integration request template

### ISSUE THREAD

**Issue by MichaelHinrichs** [automatisch/automatisch#1997]
It would make requesting an integration easier if i had a framework for what i need to say about it. do you want the API? Do i need to list functions i want? How should i write my request?

**Comment by farukaydin** [comment]
@MichaelHinrichs we thought about providing a template to request an integration but then we decided not to do so because we don't want to add additional effort for our users to request integrations but thanks for asking this.

If you can write the service and specific actions/triggers of that service you want us to build, that would be enough most of the time. If not, then we can always ask you detailed questions while working on it.

**Comment by MichaelHinrichs** [comment]
Fine.
