### ISSUE TITLE
Fix RSS Error for Google Alerts

### ISSUE THREAD

**Issue by slavakurilyak** [automatisch/automatisch#834]
automatisch v0.3.0 throws the following error when adding Google Alerts RSS:

`Cannot read properties of undefined (reading 'channel')`

Here's the RSS feed for 'chatgpt' on Google Alert:

https://www.google.com/alerts/feeds/11999357638071772629/3894422272855554182

<img width="667" alt="chatgpt" src="https://user-images.githubusercontent.com/6625584/211434010-f2167fea-5531-4231-baae-023dd64d622b.png">

<img width="869" alt="google-alerts" src="https://user-images.githubusercontent.com/6625584/211434023-22f3d1c6-10f5-484f-92d7-3f3a22338b4a.png">

**Comment by barinali** [comment]
@slavakurilyak, thanks for creating the issue. I see that Google Alerts serves an Atom 1.0 feed instead of an RSS feed. While both are a dialect of XML, their structure differs. Therefore, it fails as Automatisch supports only RSS feeds for now. However, I will see what we can do to incorporate Atom feeds within the RSS trigger.
