### ISSUE TITLE
Site can’t provide a secure connection

### ISSUE THREAD

**Issue by katrieltsepelevish** [automatisch/automatisch#846]
**Issue**
When reaching the application in development mode through HTTP instead of HTTPS an `ERR_SSL_PROTOCOL_ERROR` is raised.

**Suggestion**
A full URL with HTTP protocol should be provided on launching the application up instead of just providing the listening port. 

- Will indicate which protocol is used
- Will enable pressing the URL and redirect directly to the web through an HTTP connection

**Comment by barinali** [comment]
Hey @katrieltsepelevish, thanks for tackling this! I appreciate you improving the logged-in address in the terminal.

For the `ERR_SSL_PROTOCOL_ERROR ` scenario, it's only expected just because we do not serve the application on HTTPS by default. If necessary environment variables are provided, they should be accessible on HTTPS as well.
