### ISSUE TITLE
Invoice Ninja

### ISSUE THREAD

**Issue by farukaydin** [automatisch/automatisch#934]
### Discussed in https://github.com/automatisch/automatisch/discussions/882

<div type='discussions-op-text'>

<sup>Originally posted by **SchmalzTech** February  6, 2023</sup>
Invoice Ninja API information is published here:

https://invoice-ninja.readthedocs.io/en/latest/api.html

Aiming to use this in a self-hosted setup.</div>

Existing upvote count from GitHub discussions: 1

**Comment by ridvanakca** [comment]
I'm marking this issue as closed since we've provided 6 triggers and 4 actions for Invoice Ninja, as detailed below. If there are additional actions or triggers required, it'd be better to create new issues with specific tasks.

Triggers
#1325
#1327
#1328
#1329
#1330
#1331

Actions
#1334
#1338
#1339
#1340
